#include "example.h"

void TestFcb()
{
  bool success = true;
  if (MSG_UART) {
    while (UART_IsTxBusy(MSG_UART));
  }
  SYS_SwitchHSIClock();

  SYS_EnableAPBClock(APB_MASK_FCB0);
  SYS_EnableAHBClock(AHB_MASK_DMAC0);
  DMAC_Init();
  INT_EnableIRQ(FCB0_IRQn, MAX_IRQ_PRIORITY);

  // FPGA_ADDR must point to the address of configuration bit stream generated by Supra software
  FCB_AutoConfigDma(FPGA_ADDR, DMAC_CHANNEL7);

  SYS_SwitchPLLClock(board_hse_source());

  printf("Fcb test %s!\n", success ? "passed" : "failed");
}

