#ifndef _AGM_BOARD_INFO
#define _AGM_BOARD_INFO

#ifndef BOARD_HSI_FREQUENCY
#define BOARD_HSI_FREQUENCY 10000000
#endif

#ifndef BOARD_HSE_FREQUENCY
#define BOARD_HSE_FREQUENCY 8000000
#endif

#ifndef BOARD_PLL_FREQUENCY
#define BOARD_PLL_FREQUENCY 100000000
#endif

#ifndef BOARD_BUS_FREQUENCY
#define BOARD_BUS_FREQUENCY 100000000
#endif

#endif
